// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwrkjxicdyziupeloxzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3cmtqeGljZHl6aXVwZWxveHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjMyOTksImV4cCI6MjA2NTM5OTI5OX0.2CWq5EvXIUEtkZbsPzRAK_17iKTCuCvhGxy-hObpCCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);